version: '3.6'

services:
  node_api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.prod
    ports:
      - 5000:5000
    depends_on:
      - mongo
    networks:
      - common
    environment:
      MONGO_URI: mongodb://mongo/test

  mongo:
    container_name: mongo
    image: mongo:4.2-bionic
    volumes:
      - ./data:/data/db
    networks:
      - common

networks:
  common:
